language: r
sudo: false
cache: packages
r:
  - oldrel
  - devel

matrix:
  include:
    r: release
    after_success:
      - R CMD INSTALL $PKG_TARBALL
      - source shim_package.sh
      - Rscript -e 'covr::codecov()'
      - source unshim_package.sh
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
